config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: 'sessions#index'


# these routes are for showing users a login form, logging them in, and logging them out.
get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'

get '/signup' => 'users#new'
post '/users' => 'users#create'

get '/users/:id', to: "users#show", as: "user"
get '/users/:id/edit', to: "users#edit", as: "edit_user"
# put '/users/:id', to: "users#update"
put '/users/:id', to: "users#update", as: "user_update"
get '/users/:user_id/posts/:id', to: 'users#show_post', as: "post"
get '/users/:user_id/posts/:id/edit', to: "users#edit_post", as:"edit_post"

get 'cities', to: "cities#index", as: "cities"
get '/cities/:id', to: "cities#show", as: "city"

get '/cities/:id/post/new', to: "posts#new", as: "new_post"
post '/cities/:id/post/new', to: "posts#create"
post '/users/:user_id/posts/:id/edit', to: "posts#update_post"
delete '/users/:user_id/posts/:id', to: "posts#destroy", as: "delete_post"

post "/posts/:id/comment/new", to: "comments#create", as: "post_comment"
delete '/posts/:post_id/comment/:id', to: 'comments#destroy', as: 'delete_comment'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :city
  has_many :comments, dependent: :destroy
  validates :title, length: { in: 1..200 }
  validates :content, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :destroy
  validates :email, uniqueness: true
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
helper_method :current_user

def authorize
  redirect_to '/login' unless current_user
end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  include UsersHelper
  before_action :authorize_to_view_and_post, :reset_flash

def show
  @cities = City.all
  @city = City.find_by_id(params[:id])
  @posts = @city.posts.order("created_at desc")
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find_by_id(params[:id])
    city = City.find_by_id(post.city_id)
    post.comments.create(content: comment_params[:content], user_profile_image: current_user.image, user_id: current_user.id)
    redirect_to city_path(city)
  end

  def destroy
    comment = Comment.find_by_id(params[:id])
    post =  Post.find_by_id(comment.post_id)
    city = City.find_by_id(post.city_id)
    comment.destroy
    redirect_to city_path(city)
  end
  private
  def comment_params
    params.require(:comment).permit(:content);
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include UsersHelper
  before_action :authorize_to_view_and_post
  def new
    @post = Post.new
  end

  def create
    user = current_user
    post = user.posts.new({title: post_params[:title], content: post_params[:content], city_id: params[:id]})
    if post.save
      redirect_to post_path(user_id: current_user.id, id: post.id)
    else
      flash[:error] = post.errors.full_messages[0]
      redirect_to new_post_path
    end

  end

  def update_post
    post = Post.find_by_id(params[:id])
    post.update_attributes(post_params)
    redirect_to user_path
  end

  def destroy
    post = Post.find_by_id(params[:id])
    post.destroy
    redirect_to user_path(id: post.user_id)
  end


  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include UsersHelper
  before_action :if_logged_in, except: [:destroy]
  def index
  end

  def new
  end

  def create
  # TODO: use flash messaging to let the user know if they entered the wrong username/password
  user = User.find_by_email(params[:email])
  # If the user exists AND the password entered is correct.
  if user && user.authenticate(params[:password])
    # Save the user id inside the browser cookie. This is how we keep the user
    # logged in when they navigate around our website.
    session[:user_id] = user.id
    redirect_to user_path(user)
  else

  # use flash messaging to let the user know if they entered the wrong username/password
  flash[:error] = "Wrong email or password!"
   redirect_to '/login'
   # If user's login doesn't work, send them back to the login form.

  end
end

def destroy
  current_user = session[:user_id] = nil
  redirect_to '/login'
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  before_action :authorize, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = user.errors.full_messages[0]
      redirect_to '/signup'
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    @posts = @user.posts.order("created_at desc")
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find_by_id(params[:id])
    # name_param = params.require(:user).permit(:name)
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

    def edit_post
      @post = Post.find_by_id(params[:id])
    end

    def show_post
      @post = Post.find(params[:id])
      @user = @post.user
    end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_city, :image)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def authorize
    user = User.find_by_id(params[:user_id]||params[:id])
    if !current_user
      flash_message
    elsif current_user != user
      flash[:error] = "Sorry, but you can't look other people personal pages"
      redirect_to user_path(current_user)
    end
  end

  def authorize_to_view_and_post
    if !current_user
      flash_message
    end
  end

  def if_logged_in
    if current_user
      redirect_to user_path(current_user)
    end
  end

  def reset_flash
    flash[:error] = ""
  end

  private
  def flash_message
    flash[:error] = "You have to log in first!"
    redirect_to "/login"
  end

end

app/views/cities/show.html.erb
<br>
<br>
<br>
<br>

  <div class="row" style="height: 400px; background-image: url(<%= @city.image %>); background-position: center; background-size: cover">
    <div class="navbar div-footer">
      <div class="container">
        <br>
      <%=button_to "Add New Post", new_post_path, method: :get, class: "btn btn-danger pull-right form: {style: 'display:inline-block;'}"%>
      <%=button_to "Go Back to Profile", user_path(current_user), method: :get, class: "btn btn-info pull-right form: {style: 'display:inline-block;'}"%>
      <select name="select" id="soflow" onChange="window.location.href = '/cities/' + this.options[this.selectedIndex].value">
        <% @cities.each do |city| %>
          <%if city.id == request.original_url.split("/")[-1].to_i%>
            <option value="<%=city.id%>" selected><%=city.name%></option>
          <%else%>
            <option value="<%=city.id%>"><%=city.name%></option>
          <%end%>
        <% end %>
      </select>
      </div>
    </div>
  </div>

  <div class="wrapper-md">
    <div class="row">
      <div class="col-sm-12 offset-2">
        <% @posts.each do |post| %>
        <div class="panel">
          <div class="wrapper-lg">
            <div class="row" style="">

            <h1 class="m-t-none"><b><%= link_to post.title, post_path(user_id: post.user_id, id: post.id) %></b></h1>
            <div><p><%= post.content.split(" ")[0..50].join(" ") + "..."%><%=link_to "Read more", post_path(user_id: post.user_id, id: post.id)%></p></div>
            <div class="line line-lg b-b b-light"></div>
            <div class="text-muted">
              <i class="fa fa-user text-muted"></i> by <%= post.user.name %>
              <i class="fa fa-clock-o text-muted"></i>  <%= post.created_at %>
              <a href class="m-l-sm"><i class="fa fa-comment-o text-muted"></i> <%=post.comments.count%> comments</a>
            </div>
          </div>

    <h4 class="m-t-lg m-b">Comments</h4>
      <div>
        <%post.comments.each do |comment|%>
        <div>
          <a class="pull-left thumb-sm">
            <img src="<%=comment.user_profile_image%>" style='width:50px; height:50px'>
          </a>
          <div class="m-l-xxl m-b">
            <div>
              <a href><strong>John smith</strong></a>
              <span class="text-muted text-xs block m-t-xs">
                <%=comment.created_at%>
              </span>
            </div>
            <div class="m-t-sm"><%=comment.content%></div>
          </div>
          <%if current_user == User.find_by_id(comment.user_id)%>
          <%=button_to "Delete", delete_comment_path(post_id:comment.post_id, id: comment.id ), method: :delete, data: {confirm: "Are you sure you want to delete your comment?"}, class: "btn btn-danger", form: {style: 'display:inline-block;'}%>
          <%end%>
        </div>
      </div>
    <br>
    <%end%>

    <div class="">
      <h4 class="m-t-lg m-b">Leave a comment</h4>
      <img src="<%=current_user.image%>" style='width:50px; height:50px; float: left'>
      <%= form_for :comment, url: post_comment_path(post) do |f| %>
      <div class="col-sm-6">
        <%=f.text_field :content, class: "form-control", :placeholder => "Leave your comment" %>
      </div>
        <%=f.submit "Comment", class: "btn btn-success"%>
      <%end%>
      </div>
      </div>
    </div>
    <hr>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VagabondTeam1</title>
    <%= csrf_meta_tags %>

    <!-- bootstrap CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- added these lines. -->

<header id="header" class="navbar navbar-fixed-top bg-white-only padder-v"  data-spy="affix" data-offset-top="1">
  <div class="container">
    <div class="navbar-header">
      <button class="btn btn-link visible-xs pull-right m-r" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <i class="fa fa-bars"></i>
      </button>

      <a  href="/"><%= image_tag("http://i.imgur.com/t07VYzE.jpg")%></a>

    </div>
    <div class="collapse navbar-collapse">

      <div class="nav navbar-nav navbar-right">
          <div class="m-t-sm">
            <% if current_user %>
            <div class= 'pull-right'> Signed in as <%= current_user.name %> <%= link_to "Logout", '/logout', class: 'btn m-b-xs w-xs btn-danger' %> </div>
            <% else %>
            <%= button_to 'Login', '/login', method: :get, class: 'btn m-b-xs w-xs btn-danger pull-right', form: {style: 'display:inline-block;'} %>
            <%= button_to 'Signup', '/signup', method: :get, class: 'btn m-b-xs w-xs btn-danger pull-right', form: {style: 'display:inline-block;'} %>
            <% end %>
          </div>
      </div>
    </div>
  </div>

</header>

    <%= yield %>
  </body>
</html>

app/views/posts/new.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>


<div class="container text-center">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <hr>

      <%= form_for :post do |f| %>
      <div class = "form-group">
        Title: <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class = "form-group">
        Content: <%= f.text_area :content, class: "form-control" %>
      </div>
        <%= f.submit "Submit", class: "btn btn-danger" %>
      <% end %>

    </div>
  </div>
</div>

app/views/users/edit.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="container text-center">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <hr>

      <%= form_for :user, url: user_update_path, method: :put do |f| %>
      <div class = "form-group">
        Name: <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class = "form-group">
        Current City: <%= f.text_field :current_city, class: "form-control"  %>
      </div>
      <div class = "form-group">
        Image: <%= f.text_field :image, class: "form-control"  %>
      </div>
        <%= f.submit "Submit", class: "btn btn-danger" %>
      <% end %>

    </div>
  </div>
</div>

app/views/users/edit_post.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<%= form_for :post do |f| %>
  Title: <%= f.text_field :title %>
  Content: <%= f.text_area :content %>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/new.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

    <div class="container text-center">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">

            <hr>

            <h2>Sign Up to Explore the World with Us</h2>
          </br>
          <div class="col-md-12 text-danger">
            <%=flash[:error] %>
        </div>

            <%= form_for :user, url: '/users' do |f| %>
            <div class = "form-group">
            <%= f.text_field :name, class: "form-control", placeholder: "Name"%>
            </div>
            <div class = "form-group">
            <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
            </div>
            <div class = "form-group">
            <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
            </div>
              <div class = "form-group">
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm your password" %>
            </div>
            <%= f.hidden_field :image, :value => "http://i.imgur.com/en3Tpt6.png" %>
            <div class = "form-group">
              <hr>
            <%= f.submit "Submit", class: "btn btn-danger"%>
            </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/users/partials/_user_info.html.erb
  <div class="col-lg-3">
    <div class="panel panel-default">
      <br>
      <br>
      <br>
      <div class="panel-body">
        <div class="clearfix text-center m-t">
          <div class="inline">
              <div class="thumb-xl avatar m-t-n-xxl">
                <img src="<%= @user.image %>" class="img-circle">
              </div>
              <br>
            <div class="h4 m-t m-b-xs"><%= @user.name %></div>
            <br>
            <div><small class="text-muted m-b"><%=@user.current_city%></small></div>
            <br>
            <small class="text-muted m-b">  <%=@user.created_at.getlocal%></small>
            <br>
            <br>
            <%=button_to "Edit My Profile", edit_user_path, method: :get, class: "btn btn-info"%>
            <br>
          </div>
        </div>
      </div>
      <footer class="panel-footer bg-info text-center no-padder">
        <div class="row no-gutter">
          <div class="col-xs-4">
            <div class="wrapper">
              <span class="m-b-xs h3 block text-white">245</span>
              <small class="text-muted">Followers</small>
            </div>
          </div>
          <div class="col-xs-4 dk">
            <div class="wrapper">
              <span class="m-b-xs h3 block text-white">55</span>
              <small class="text-muted">Following</small>
            </div>
          </div>
          <div class="col-xs-4">
            <div class="wrapper">
              <span class="m-b-xs h3 block text-white"><%= user.posts.count %> </span>
              <small class="text-muted">Posts</small>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>

app/views/users/show.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


<%= render partial: 'users/partials/user_info', locals: {user: @user} %>


<%=button_to "Explore Cities", city_path(City.first), method: :get, class: "btn btn-info"%>

<div class="wrapper-md">
  <div class="row">
    <div class="col-sm-8">
      <div class="blog-post">
          <%=flash[:error] %>
        </div>
        <% @posts.each do |post| %>
        <div class="panel">
        <div class="wrapper-lg">
          <h2 class="m-t-none"><%= link_to post.title, post_path(user_id: post.user_id, id: post.id) %></h2>
          <div>
            <p><%= post.content.split(" ")[0..50].join(" ") + "..."%><%=link_to "Read more"%></p>
          </div>
          <%=button_to "Edit Post", edit_post_path(user_id:post.user_id, id: post.id), method: :get, class: "btn btn-info btn-sm", form: {style: 'display:inline-block;'}%>
          <%=button_to "Delete Post", delete_post_path(user_id:post.user_id, id:post.id), method: :delete, class: "btn btn-danger btn-sm", form: {style: 'display:inline-block;'}, data: {confirm: "Are you sure you want to delete #{post.title}?"}%>
          <div class="line line-lg b-b b-light"></div>
          <div class="text-muted">
            <i class="fa fa-user text-muted"></i> by <%= @user.name %>
            <i class="fa fa-clock-o text-muted"></i>  <%= @user.created_at %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show_post.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<%= render partial: 'users/partials/user_info', locals: {user: @user} %>

<%=button_to "Go Back to Profile", user_path, method: :get, class: "btn btn-info pull-right form: {style: 'display:inline-block;'}"%>
<%=button_to "Explore Cities", city_path(City.first), method: :get, class: "btn btn-info"%>

<div class="wrapper-md">
  <div class="row">
    <div class="col-sm-8">
      <div class="blog-post">
        <div class="panel">
        <div class="wrapper-lg">
          <h2 class="m-t-none"><%= @post.title %></h2>
          <div>
            <p><%= @post.content %></p>
          </div>
          <div class="line line-lg b-b b-light"></div>
          <div class="text-muted">
            <i class="fa fa-user text-muted"></i> by <%= @user.name %>
            <i class="fa fa-clock-o text-muted"></i>  <%= @user.created_at %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>